spring.application.name=order-service
restaurant-catalog-api.url=http://localhost:8081/api/restaurants

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=ordering
spring.datasource.username=user
spring.datasource.password=password

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:sql/data.sql

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

spring.rabbitmq.kdg.exchange-name=kdg_exchange
spring.rabbitmq.kdg.order-placed-binding=order.placed
spring.rabbitmq.kdg.order-rejected-queue=order_rejected_queue
spring.rabbitmq.kdg.order-rejected-binding=order.rejected
spring.rabbitmq.kdg.order-accepted-order-queue=order_accepted_order_queue
spring.rabbitmq.kdg.order-accepted-order-binding=order.accepted.order_service
spring.rabbitmq.kdg.order-ready-order-queue=order_ready_order_queue
spring.rabbitmq.kdg.order-ready-order-binding=order.ready.order_service
spring.rabbitmq.kdg.order-picked-up-queue=order_picked_up_queue
spring.rabbitmq.kdg.order-picked-up-binding=order.pickedUp
spring.rabbitmq.kdg.order-delivered-queue=order_delivered_queue
spring.rabbitmq.kdg.order-delivered-binding=order.delivered